/** Signal emitted by trend-detector when a launchable trend is found */
export interface LaunchSignal {
  keyword: string;
  score: number;
  reasoning: string;
  suggestedName: string;
  suggestedTicker: string;
  context: Record<string, unknown>;
  imageUrls: string[];
}

/** Token metadata generated by AI */
export interface TokenMetadata {
  name: string;
  ticker: string;
  description: string;
}

/** Exit stage configuration */
export interface ExitStage {
  stage: 1 | 2 | 3;
  tokenAmountPct: number;
  trigger: string;
}

/** Position snapshot for monitoring */
export interface PositionSnapshot {
  tokenId: number;
  mintAddress: string;
  bondingProgress: number;
  pricePerToken: number;
  volumeLast5m: number;
  holderCount: number;
  unrealizedPnlSol: number;
}

/** Trend score result from Claude */
export interface TrendScoreResult {
  score: number;
  reasoning: string;
  suggestedName: string;
  suggestedTicker: string;
}

/** Wallet info for pool management */
export interface WalletInfo {
  address: string;
  derivationPath: string;
  solBalance: number;
  isActive: boolean;
  lastUsedAt: Date | null;
}
