/** Signal emitted by trend-detector when a launchable trend is found */
export interface LaunchSignal {
  keyword: string;
  score: number;
  reasoning: string;
  suggestedName: string;
  suggestedTicker: string;
  context: Record<string, unknown>;
  imageUrls: string[];
}

/** Token metadata generated by AI */
export interface TokenMetadata {
  name: string;
  ticker: string;
  description: string;
}

/** Exit stage configuration */
export interface ExitStage {
  stage: 1 | 2 | 3;
  tokenAmountPct: number;
  trigger: string;
}

/** Position snapshot for monitoring */
export interface PositionSnapshot {
  tokenId: number;
  mintAddress: string;
  bondingProgress: number;
  pricePerToken: number;
  volumeLast5m: number;
  holderCount: number;
  unrealizedPnlSol: number;
}

/** Trend score result from Claude */
export interface TrendScoreResult {
  score: number;
  reasoning: string;
  suggestedName: string;
  suggestedTicker: string;
}

/** Reference to a specific tweet for fxtwitter enrichment */
export interface TweetRef {
  tweetId: string;
  screenName: string;
}

/** Enriched tweet data from fxtwitter API */
export interface EnrichedTweet {
  text: string;
  likes: number;
  retweets: number;
  views: number;
  authorFollowers: number;
  hasMedia: boolean;
  createdAt: string;
}

/** Context passed to the scorer after fxtwitter enrichment */
export interface ScorerContext {
  keyword: string;
  sampleTweets: EnrichedTweet[];
  totalMentions: number;
  avgEngagement: number;
  topTweetViews: number;
  hasImagesOrMemes: boolean;
}

/** Wallet info for pool management */
export interface WalletInfo {
  address: string;
  derivationPath: string;
  solBalance: number;
  isActive: boolean;
  lastUsedAt: Date | null;
}
